import streamlit as st
from langchain_core.messages import AIMessage, HumanMessage
from torchgen.packaged.autograd.context import with_native_function_with_differentiability_info_and_key

from rag_engine import RAGEngine

# 1. Page Configuration
st.set_page_config(page_title="PyRAG-Portico", page_icon="", layout="centered")
st.title("Ithaka (Portico) Workbench Intelligence")
#st.caption("Grounded AI Q&A Engine powered by project Knowledge Base")

# 2. Lazy-load the backend engine using cache parameters
# This ensures we only load the LLM and FAISS files ONCE, not on every keystroke.
# @st.cache_resource
# def initialize_rag_backend():
#     return RAGEngine()

# Cache the RAG engine initialization in memory across app reruns
@st.cache_resource(show_spinner="Initializing RAG Engine & Loading Indexes...")

def load_rag_engine()->RAGEngine:
    """
        Instantiates the RAG engine once and persists it in memory.
        Prevents costly index reloading on every user chat interaction.
    """
    return RAGEngine()

try:
    #engine = initialize_rag_backend()
    engine = load_rag_engine()
    chain = engine.get_chain()
except Exception as e:
    st.error(f"Failed to initialize backend engine. Ensure FAISS index exist. Error {e}")
    st.stop()

# 3. Initialize Persistent Memory Session States
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# 4. Display Existing Chat Transcript
# Streamlit clears the screen on every run; we must manually redraw past messages
for message in st.session_state.chat_history:
    if isinstance(message, HumanMessage):
        with st.chat_message("user"):
            st.markdown(message.content)
    elif isinstance(message, AIMessage):
        with st.chat_message("assistant"):
            st.markdown(message.content)

# 5. Handle New User Interactions
if user_query := st.chat_input("Ask Ithaka (Portico) project related questions."):
    # Render user message on screen instantly
    with st.chat_message("user"):
        st.markdown(user_query)

    # Render user message on screen instantly
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        full_response = ""

        try:
            # We use .stream() instead of .invoke() for an elite UX experience.
            # Tokens stream onto the screen live as they are generated by the model.
            for chunk in chain.stream(
                    {
                        "chat_history": st.session_state.chat_history,
                        "question": user_query
                    }
            ):
                full_response += chunk
                response_placeholder.markdown(full_response + "▌")

            # Remove cursor block once streaming concludes
            response_placeholder.markdown(full_response)
        except Exception as e:
            st.error(f"An execution error occurred: {str(e)}")
            full_response = "I encountered an error processing that request."

        # 6. Commit the current turn to persistent memory state
        st.session_state.chat_history.append(HumanMessage(content=user_query))
        st.session_state.chat_history.append(AIMessage(content=full_response))



